//
// Copyright (c) 2019 Contributors to the Eclipse Foundation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

[[jsonb]]

== JSON-B Integration

The MicroProfile GraphQL project depends on JSON-B 1.0 APIs. Implementations of MP GraphQL are encouraged to use JSON-B
implementations for consistency.

JSON-B annotations can be used to help determine schema information as well as data transformation at runtime. In all
cases, annotations in the `org.eclipse.microprofile.graphql` package will trump JSON-B annotations if there is a
conflict.

=== Schema Definition

The `@JsonbProperty` annotation's `value` attribute can be used to modify the field name of a type, input type or both
- depending on whether the annotation is placed on the getter method, setter method, or Java field, respectively.

For example, suppose you have the following Java code (with properties conforming to the JavaBean spec for `name`,
`weight`, and `quantity`):

.JsonbProperty Java Code Example
[source,java,numbered]
----
public class Widget {
    @JsonbProperty("widgetName")
    private String name;
    private double weight;
    private int quantity;
    //...

    @JsonbProperty("shippingWeight")
    public double getWeight() {
        return weight;
    }
    //...

    @JsonbProperty("qty")
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
----

That would create a schema like this:

.JsonbProperty Schema Example
[source,graphql,numbered]
----
type Widget {
    widgetName: String
    quantity: Int!
    shippingWeight: Float!
}

input WidgetInput {
    widgetName: String
    qty: Int!
    weight: Float!
}
----

Similarly, the `@JsonbTransient` annotation can be used to ignore certain fields from the type or input type in the 
schema. The same rules apply: if the annotation is on the getter, then the field is ignored in the type; if the
annotation is on the setter, then the field is ignored in the input type; if the annotation is on the Java field, it
is ignored in both.

Here is an example, similar to the previous example:

.JsonbTransient Java Code Example
[source,java,numbered]
----
public class Widget {
    @JsonbTransient
    private String name;
    private double weight;
    private int quantity;
    //...

    @JsonbTransient
    public double getWeight() {
        return weight;
    }
    //...

    @JsonbTransient
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
}
----

That would create a schema like this:

.JsonbTransient Schema Example
[source,graphql,numbered]
----
type Widget {
    quantity: Int!
}

input WidgetInput {
    weight: Float!
}
----

=== Runtime Data Transformation

JSON-B annotations like `@JsonbDateFormat` and `@JsonbNumberFormat` can be used to transform data at runtime.

For example, suppose you have a Java entity like this:

.JsonbDateFormat Java Code Example
[source,java,numbered]
----
public class Widget {
    @JsonbDateFormat("yyyy-MM-dd")
    private LocalDate constructionDate;
}
----

A query that requests a Widget's construction date would get a result like this:

.JsonbTransient Schema Example
[source,json,numbered]
----
{
    "constructionDate": "2019-09-16"
}
----

If no `@Description` annotation is provided for a date field, the date format string specified in the `@JsonbDateFormat` annotation 
will be used as the field's description, or the default date format in the case there is not `@JsonbDateFormat` annotation. 

If a `@Description` annotation is provided for a date field, the date format string specified in the `@JsonbDateFormat` annotation 
will be appended to the given description in brackets `(...)`, or the default date format in the case there is not `@JsonbDateFormat` annotation. 

Example:

[source,java,numbered]
----

private LocalDate dateObject;

@Description("This is another date")
private LocalDate anotherDateObject;

@JsonbDateFormat("MM dd yyyy")
@Description("This is a formatted date")
private LocalDate formattedDateObject;
----

will result in:

[source,graphql,numbered]
----
type ScalarHolder {
  #yyyy-MM-dd
  dateObject: Date

  #This is another date (yyyy-MM-dd)
  anotherDateObject: Date
  
  #This is a formatted date (MM dd yyyy)
  formattedDateObject: Date
  #...
}
----

=== JSON-B Annotations vs MP GraphQL Annotations

The `@JsonbProperty` annotation can be used interchangeably with `@Name`. If both annotations are used on the same
member, the `@Name` annotation will take precendence when determining the field name in the schema and the JSON property
in the response.

Likewise, `@JsonbTransient` can be used interchangeably with `@Ignore`. 